 export enum roles {
  MASTER = 'MASTER',
  SUBADMIN = 'SUBADMIN',
  RECEPTION = 'RECEPTION',
  HOD = 'HOD',
  TELEADMIN = 'TELEADMIN',
  STAFF = 'STAFF',
  STUDENT = 'STUDENT',
  TELECALLER = 'TELECALLER',
}