CREATE DATABASE IF NOT EXISTS auth;
CREATE DATABASE IF NOT EXISTS institute;
CREATE DATABASE IF NOT EXISTS telecalling;
CREATE DATABASE IF NOT EXISTS training;
CREATE DATABASE IF NOT EXISTS payment;
CREATE DATABASE IF NOT EXISTS reception;
CREATE DATABASE IF NOT EXISTS notifyandlog;
CREATE DATABASE IF NOT EXISTS openvidu;
CREATE DATABASE IF NOT EXISTS content;
CREATE DATABASE IF NOT EXISTS ticket;
CREATE DATABASE IF NOT EXISTS placement;

CREATE USER 'patron'@'%' IDENTIFIED BY '123456';

GRANT ALL PRIVILEGES ON *.* TO 'patron'@'%';

FLUSH PRIVILEGES;