export enum Role {
  MASTER = 'MASTER',
  HOD = 'HOD',
  SUBADMIN = 'SUBADMIN',
  STUDENT = 'STUDENT',
  STAFF = 'STAFF',
  TELECALLER = 'TELECALLER',
  TELEADMIN = 'TELEADMIN',
  RECEPTION = 'RECEPTION',
}
